require: rubocop-rspec

Metrics/LineLength:
  Max: 99

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Max: 55

Metrics/ClassLength:
  Max: 110